export const LOADING_STATE_CHANGE = 'LOADING_STATE_CHANGE'

// img-split module
export const INIT_AREA_INFO = 'INIT_AREA_INFO'
export const SET_IMAGE_URL = 'SET_IMAGE_URL'
export const SET_BACKGROUND_URL = 'SET_BACKGROUND_URL'
export const SET_IMAGE_WIDTH = 'SET_IMAGE_WIDTH'
export const SET_AREA_COUNT = 'SET_AREA_COUNT'
export const NAV_PREV_GO = 'NAV_PREV_GO'
export const NAV_NEXT_GO = 'NAV_NEXT_GO'
export const SET_SCROLL_WIDTH = 'SET_SCROLL_WIDTH'

// first step
export const ONE_SET_CURRENT_AREA_INDEX = 'ONE_SET_CURRENT_AREA_INDEX'
export const ONE_CANCEL_CURRENT_AREA_INDEX = 'ONE_CANCEL_CURRENT_AREA_INDEX'
export const ONE_ADD_OR_UPDATE_CURRENT_AREA_COORDS = 'ONE_ADD_OR_UPDATE_CURRENT_AREA_COORDS'
export const ONE_DELETE_CURRENT_AREA_COORD = 'ONE_DELETE_CURRENT_AREA_COORD'
export const ONE_SET_CURRENT_AREA_COORD_FPCUS_INDEX = 'ONE_SET_CURRENT_AREA_COORD_FPCUS_INDEX'
export const ONE_CANCEL_CURRENT_AREA_COORD_FPCUS_INDEX = 'ONE_CANCEL_CURRENT_AREA_COORD_FPCUS_INDEX'

// second step
export const TWO_SET_CURRENT_AREA_INDEX = 'TWO_SET_CURRENT_AREA_INDEX'
export const TWO_CANCEL_CURRENT_AREA_INDEX = 'TWO_CANCEL_CURRENT_AREA_INDEX'
